[package]
name = "advent-of-code-2016"
version = "0.1.0"
authors = ["Olivier Chass√© St-Laurent <oliviercsl@gmail.com>"]
edition = "2018"

[dependencies]
md5 = "0.7.0"
permutohedron = "0.2.4"
regex = "1.5.4"
